const fs = require('fs');
const assert = require('assert');
const path = require('path');
const here = __dirname;
const browser = fs.readFileSync(path.join(here,'browser-engine.js'),'utf8');
const app = fs.readFileSync(path.join(here,'..','frontend','app.js'),'utf8');
const server = fs.readFileSync(path.join(here,'server.js'),'utf8');
const vpn = fs.readFileSync(path.join(here,'vpn.js'),'utf8');
assert(browser.includes('this.creatingSessions = 0;'));
assert(browser.includes('getByTabId(tabId)'));
assert(browser.includes("code: 'BROWSER_CAPACITY'"));
assert(browser.includes('finally {\n      this.creatingSessions'));
assert(browser.includes('!s.navigationActive &&'));
assert(app.includes('if (e.code === \'BROWSER_CAPACITY\') addLog'));
assert(!app.match(/if \(e\.code === 'BROWSER_CAPACITY'\)[\s\S]{0,300}navigateUrl\(/));
assert(app.includes("/api/vpn/test"));
assert(server.includes("app.post('/api/vpn/test'"));
assert(vpn.includes('Socks5ProxyAgent'));
assert(vpn.includes('async test(profileId'));
console.log('Browser/VPN regression checks: PASS');
