const fs = require('fs');
const path = require('path');
const s = fs.readFileSync(path.join(__dirname, 'server.js'), 'utf8');
const vpnJs = fs.readFileSync(path.join(__dirname, 'vpn.js'), 'utf8');
const frontendJs = fs.readFileSync(path.join(__dirname, '../frontend/app.js'), 'utf8');
function ok(name, cond) { if (!cond) throw new Error(`FAIL ${name}`); console.log('PASS', name); }
ok('logical robot bundle config exists', s.includes('ROBOT_BUNDLE_SIZE'));
ok('adaptive host policy exists', s.includes('hostConcurrencyLimit(job, host)') && s.includes('noteHostSuccess(job, host)') && s.includes('noteHostError(job, host)'));
ok('frontier accepts dynamic host limits', s.includes('typeof perHostLimit === "function"'));
ok('external HTML links are recorded', s.includes('if (type === "html" && !internal) return true;'));
ok('background sitemap loading', s.includes('void loadSitemaps(job)'));
ok('browser discoveries return to crawler', s.includes('job.browserDiscoveredCount') && s.includes('browser-network'));
ok('broad page scan exists', s.includes('broad-scan') && s.includes('MAX_BROAD_SCAN_CHARS'));
ok('GET form actions preserve target', s.includes('data-veyra-action') && s.includes('GET form submissions replace the URL query component'));
ok('explicit engine modes exist', s.includes('OPEN_ENGINE_MODES') && s.includes('engineMode') && s.includes('crawlerEnabled'));
ok('page accelerator is bounded and fast', s.includes('crawlerPageAccelerator') && s.includes('crawlerPageWarmMs') && s.includes('crawlerPageMaxResources'));
ok('page accelerator skips navigation expansion', s.includes('job.pageAccelerator && u !== job.root'));
ok('combined mode preserves crawler concurrency', s.includes('!job?.pageAccelerator && browserEngine'));
ok('seed crawl cannot hijack page accelerator', s.includes('!CFG.crawlerPageAccelerator || old.pageAccelerator'));
ok('proxy-only mode can skip crawler', s.includes('state: "disabled"') && s.includes('shouldStartCrawlerForEngineMode'));
ok('browse crawler opens use bounded page accelerator', s.includes('const job = createJob(root, { pageAccelerator: CFG.crawlerPageAccelerator });'));
ok('critical asset preload pipeline exists', s.includes('criticalPreloadHtml') && s.includes('preloadCandidates') && s.includes('PROXY_CRITICAL_PRELOAD_LIMIT'));
ok('inline asset warm scan exists', s.includes('extractInlineWarmUrls') && s.includes('PROXY_INLINE_WARM_SCAN_CHARS'));
ok('request coalescing prevents duplicate foreground fetches', s.includes("fetchInflight") && s.includes("canCoalesce"));
ok('Mongo persistence and L2 cache are wired', fs.existsSync(path.join(__dirname, "mongo-store.js")) && s.includes("mongoStore"));
ok('auto heavy pages can race proxy and Chromium', frontendJs.includes('key: "combined", proxy: true, crawler: true, browser: true, race: true') && frontendJs.includes('background: true'));
ok('proxy referrer recovery is validated', s.includes('function proxyRefererCanonical') && s.includes('proxyRefererCanonical(req)'));

ok('retryable crawl failures requeue', s.includes('targetFrontier.requeue'));
ok('render critical resources have a dedicated frontier', s.includes('criticalResourceFrontier'));
ok('status includes new robot bundle configuration', s.includes('robotBundleSize'));
ok('browser binary ensure script is wired', fs.existsSync(path.join(__dirname, 'ensure-browser.js')) && fs.existsSync(path.join(__dirname, 'render.yaml')));
const pkg = JSON.parse(fs.readFileSync(path.join(__dirname,'package.json'),'utf8'));
ok('prestart browser ensure is wired', pkg.scripts && pkg.scripts.prestart === 'node ensure-browser.js');
ok('VPN scheduled rotation exists', vpnJs.includes('VPN_ROTATION_INTERVAL_MS') && vpnJs.includes('this.rotationIntervalMs'));
ok('VPN different-IP guard exists', vpnJs.includes('rotationSameIpGuard') && vpnJs.includes('oldHealth?.exitIp'));
ok('VPN rotation rate limit exists', vpnJs.includes('VPN_ROTATION_MIN_GAP_MS') && vpnJs.includes('VPN_ROTATION_RATE_LIMIT'));
console.log('Veyra static regression checks passed');
