"use strict";
const assert = require("assert");
const { Script } = require("vm");
const { createSourceViewerStore, parseSourceScheme, sourcePage, consolePage } = require("../src/services/console-ui");
const { pageActionsRuntime } = require("../src/browser/page-actions-runtime");

(async () => {
  const store = createSourceViewerStore({ maxEntries: 2, maxBytes: 64, ttlMs: 25 });
  const first = store.create({ url: "https://example.test/a?x=1", text: "<p>first</p>", contentType: "text/html" });
  assert.match(first.schemeUrl, /^veyra:\/\/view_source\/[A-Za-z0-9_-]{20,40}\/[A-Za-z0-9_-]+$/);
  assert.deepEqual(parseSourceScheme(first.schemeUrl), { id: first.id, link: first.link, uri: first.schemeUrl });
  assert.equal(parseSourceScheme("veyra://view_source/not-valid/path"), null);
  assert.equal(parseSourceScheme(`${first.schemeUrl}?ignored=1`), null);
  assert.equal(parseSourceScheme(first.schemeUrl.replace(`/${first.link}`, `//${first.link}`)), null);
  assert.equal(store.get(first.id, `${first.link}tampered`), null);
  assert.equal(store.get(first.id, first.link).text, "<p>first</p>");
  const injected = store.create({ url: "https://example.test/x", text: "</script><script>alert('owned')</script>\nHello & <world>", contentType: "text/html" });
  const html = sourcePage({ ...store.get(injected.id, injected.link), ...injected });
  assert.match(html, /<pre>&lt;\/script&gt;&lt;script&gt;alert\(&#39;owned&#39;\)&lt;\/script&gt;/, "captured markup must render as escaped, inert source text");
  assert.doesNotMatch(html, /<script|VEYRA VERIFIED|Copy source|Copy Veyra link|Open page|text\/html|HTTP 200|\d+ lines|veyra:\/\/view_source\//i, "source page should contain no oversized chrome, metadata or controls");
  assert.match(html, /color-scheme:dark/);
  assert.match(html, /ui-monospace/);
  const consoleMarkup = consolePage();
  assert.match(consoleMarkup, /VEYRA VERIFIED/);
  assert.match(consoleMarkup, /<svg/);
  assert.equal(store.get(first.id, first.link), null, "aggregate retention budget should evict the oldest snapshot");
  const expiryStore = createSourceViewerStore({ ttlMs: 5 });
  const expiring = expiryStore.create({ url: "https://example.test/short-lived", text: "temporary" });
  await new Promise(resolve => setTimeout(resolve, 10));
  assert.equal(expiryStore.get(expiring.id, expiring.link), null, "source links should expire automatically");

  for (const name of ["AI_API_KEY", "AI_API_BASE_URL", "AI_API_URL", "AI_API_PATH", "AI_API_KEY_HEADER", "AI_API_KEY_PREFIX", "AI_API_HEADERS_JSON", "AI_API_TOKEN_FIELD", "AI_API_STRUCTURED_OUTPUT", "AI_API_OPTIONS_JSON", "AI_API_REQUEST_TEMPLATE_JSON", "AI_API_RESPONSE_PATH", "AI_PROVIDER", "AI_PROVIDER_NAME", "AI_ANSWER_MODEL", "OPENAI_API_KEY", "OPENAI_API_BASE", "GOOGLE_SEARCH_API_KEY", "GOOGLE_API_KEY", "GOOGLE_SEARCH_CX", "GOOGLE_CSE_ID", "BRAVE_SEARCH_API_KEY", "BING_SEARCH_API_KEY"]) delete process.env[name];
  process.env.VEYRA_CHROMIUM_ENABLED = "false";
  process.env.INDEX_AI_FINDINGS = "false";
  process.env.FRONTEND_ORIGIN = "https://homekidchud.github.io";
  const { app, mongoStore, rewriteHtml } = require("../src/server");
  mongoStore.enabled = false;
  mongoStore.uri = "";
  const proxiedHtml = rewriteHtml("<!doctype html><html><head></head><body><p>Shortcut fixture</p></body></html>", "https://fixture-source.test/page", "source-view-test-session");
  const pageRuntime = proxiedHtml.match(/<script data-veyra-runtime>([\s\S]*?)<\/script>/)?.[1];
  assert.ok(pageRuntime, "proxied pages should receive the Veyra page-action runtime");
  new Script(pageRuntime);
  for (const capability of ["contextmenu", "touchstart", "View page source  ·  Ctrl+U", "Inspect element"]) assert.ok(pageRuntime.includes(capability), `missing page action: ${capability}`);
  assert.ok(pageRuntime.includes("key!=='u'"), "Ctrl+U should be handled locally inside the page frame");
  assert.ok(pageRuntime.includes("emit('document-navigation',viewerUrl.href"), "source view should use the browser's supported fast-proxy navigation event");
  assert.ok(pageRuntime.includes("payload.webUrl") && pageRuntime.includes("payload.schemeUrl"), "source navigation should open the stored source page and retain its Veyra URI");
  assert.equal(pageRuntime.includes("/api/browser/session/'+encodeURIComponent(SESSION_ID)+'/navigate"), false, "proxy session IDs must not be sent to the Chromium-only navigation API");
  assert.ok(pageRuntime.includes("emit('document-navigation',link)"), "open-link should use the browser's recognized navigation event");
  assert.ok(pageRuntime.includes("item('Reload page',()=>location.reload())"), "reload should refresh the proxied document directly");
  assert.ok(pageRuntime.includes("type:'veyra:shortcut',key:'I',code:'KeyI',ctrlKey:true,metaKey:false,shiftKey:true"), "Inspect Element should open the existing Developer Tools UI");
  assert.ok(pageRuntime.includes("bridge.call('dom.nodeAt'") && pageRuntime.includes("bridge.emit('dom.select'"), "Inspect Element should select the highlighted target in Developer Tools");
  assert.equal(pageRuntime.includes("veyraInspectPanel"), false, "Inspect Element should not open the replacement popup UI");
  assert.equal(pageActionsRuntime().includes("contextmenu.open-link"), false, "menu must not emit unsupported custom action events");
  let fetches = 0;
  let nextResponse = { ok: true, status: 200, contentType: "text/html; charset=utf-8", body: Buffer.from("<!doctype html><html><body><script>alert('owned')</script><h1>Fixture</h1></body></html>"), finalUrl: "https://fixture-source.test/page" };
  app.locals.veyraSourceAssertPublic = async url => {
    const host = new URL(url).hostname.toLowerCase();
    if (host === "127.0.0.1" || host === "localhost") throw Object.assign(new Error("Private address blocked"), { code: "SSRF_BLOCKED", status: 403 });
  };
  app.locals.veyraSourceFetch = async (url, options) => {
    fetches += 1;
    assert.equal(options.engine, "view-source");
    assert.equal(options.noCache, true);
    assert.equal(options.maxBytes, 1024 * 1024);
    if (url.includes("unsupported")) nextResponse = { ...nextResponse, contentType: "application/pdf" };
    else nextResponse = { ...nextResponse, contentType: "text/html; charset=utf-8" };
    return nextResponse;
  };
  const server = app.listen(0, "127.0.0.1");
  try {
    await new Promise((resolve, reject) => { server.once("listening", resolve); server.once("error", reject); });
    const base = `http://127.0.0.1:${server.address().port}`;
    const consoleResponse = await fetch(`${base}/console`);
    const consoleHtml = await consoleResponse.text();
    assert.equal(consoleResponse.status, 200);
    assert.match(consoleHtml, /data-page="overview"/);
    assert.match(consoleHtml, /data-page="logs"/);
    assert.match(consoleHtml, /data-page="source"/);
    const consoleScripts = [...consoleHtml.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(match => match[1]);
    assert.equal(consoleScripts.length, 3, "console should include dashboard, operational metrics and AI readiness scripts");
    consoleScripts.forEach(script => new Script(script));
    assert.match(consoleHtml, /providerHealth/);
    assert.match(consoleHtml, /acquisitionHealth/);
    assert.match(consoleHtml, /answerReadiness/);
    assert.match(consoleHtml, /configure a provider key, endpoint, and model in Render/);
    assert.match(consoleHtml, /data\.provider/);
    const diagnosticsResponse = await fetch(`${base}/api/search/diagnostics`);
    const diagnostics = await diagnosticsResponse.json();
    assert.equal(diagnosticsResponse.status, 200);
    assert.equal(diagnostics.ok, true);
    assert.ok(diagnostics.providers);
    const response = await fetch(`${base}/api/view-source`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ url: "https://fixture-source.test/page" }) });
    const payload = await response.json();
    assert.equal(response.status, 200);
    assert.equal(payload.ok, true);
    assert.match(payload.schemeUrl, /^veyra:\/\/view_source\//);
    assert.equal(payload.url, "https://fixture-source.test/page");
    assert.equal(payload.bytes > 0, true);
    const parsed = parseSourceScheme(payload.schemeUrl);
    assert.equal(parsed.id, payload.id);
    assert.equal(Buffer.from(parsed.link, "base64url").toString("utf8"), payload.url);

    const pageResponse = await fetch(`${base}${payload.webUrl}`);
    const page = await pageResponse.text();
    assert.equal(pageResponse.status, 200);
    const sourceCsp = pageResponse.headers.get("content-security-policy");
    assert.match(sourceCsp, /default-src 'none'/);
    assert.match(sourceCsp, /script-src 'none'/);
    assert.match(sourceCsp, /frame-ancestors 'self' https:\/\/homekidchud\.github\.io/);
    assert.doesNotMatch(sourceCsp, /frame-ancestors 'none'/, "the secure source viewer must be embeddable in the configured Veyra browser UI");
    assert.match(pageResponse.headers.get("x-content-type-options"), /nosniff/i);
    assert.equal(page.includes("</script><script>alert('owned')"), false);
    assert.equal(page.includes("<h1>Fixture</h1>"), false, "response HTML must be presented as source text, not interpreted markup");
    assert.equal(page.includes("&lt;script&gt;alert(&#39;owned&#39;)") , true);

    const tampered = await fetch(`${base}/view_source/${payload.id}/${payload.link}x`);
    assert.equal(tampered.status, 404);
    const privateUrl = await fetch(`${base}/api/view-source`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ url: "http://127.0.0.1/admin" }) });
    assert.equal(privateUrl.status, 403);
    const secretUrl = await fetch(`${base}/api/view-source`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ url: "https://fixture-source.test/page?access_token=notshareable" }) });
    assert.equal(secretUrl.status, 400);
    assert.equal(fetches, 1, "invalid, private and credential-bearing targets must be rejected before fetching");

    const badType = await fetch(`${base}/api/view-source`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ url: "https://fixture-source.test/unsupported" }) });
    assert.equal(badType.status, 415);
    assert.equal((await badType.json()).code, "SOURCE_CONTENT_TYPE_UNSUPPORTED");
    console.log("Source-view store, custom URI, inert rendering and Express capture routes passed local integration tests");
  } finally {
    delete app.locals.veyraSourceFetch;
    delete app.locals.veyraSourceAssertPublic;
    await new Promise(resolve => server.close(resolve));
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
